//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNLCI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DB : DbContext
    {
        public DB()
            : base("name=DB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Alumno> Alumno { get; set; }
        public virtual DbSet<bitacora> bitacora { get; set; }
        public virtual DbSet<Carrera> Carrera { get; set; }
        public virtual DbSet<Grupo> Grupo { get; set; }
        public virtual DbSet<Justificante> Justificante { get; set; }
        public virtual DbSet<Medico> Medico { get; set; }
        public virtual DbSet<Tutor> Tutor { get; set; }
        public virtual DbSet<Ingreso> Ingreso { get; set; }
        public virtual DbSet<Pase_de_salida> Pase_de_salida { get; set; }
    
        public virtual int Activar(string identificador)
        {
            var identificadorParameter = identificador != null ?
                new ObjectParameter("identificador", identificador) :
                new ObjectParameter("identificador", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Activar", identificadorParameter);
        }
    
        public virtual int Desactivar(string identificador)
        {
            var identificadorParameter = identificador != null ?
                new ObjectParameter("identificador", identificador) :
                new ObjectParameter("identificador", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Desactivar", identificadorParameter);
        }
    
        public virtual int importar(string rutaArchivo)
        {
            var rutaArchivoParameter = rutaArchivo != null ?
                new ObjectParameter("RutaArchivo", rutaArchivo) :
                new ObjectParameter("RutaArchivo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("importar", rutaArchivoParameter);
        }
    }
}
