//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNLCI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ingreso
    {
        public string Matricula { get; set; }
        public string Nombre { get; set; }
        public string Primer_apellido { get; set; }
        public string Segundo_apellido { get; set; }
        public string Email_institucional { get; set; }
        public string CURP { get; set; }
        public string Plan_de_Estudios_Cve { get; set; }
        public string Plan_de_Estudios { get; set; }
        public string Médico_Cv_Filiación { get; set; }
        public string Médico_Institución_Médica { get; set; }
        public string Médico_No_U_de_Salud { get; set; }
        public string Grupo_Referente { get; set; }
        public string Médico_Unidad_de_Salud { get; set; }
        public string Dom_Colonia { get; set; }
        public string Cd__Localidad { get; set; }
        public string Dom_CP { get; set; }
        public string Dom_Ciudad { get; set; }
        public string Dom_Ent_Fed { get; set; }
        public string Periodo_Escolar_Inicio { get; set; }
        public string Calle { get; set; }
        public string Municipio { get; set; }
        public string Tel_Celular { get; set; }
        public string E_mail { get; set; }
        public string Tutor_Nombre { get; set; }
        public string Tutor_celular { get; set; }
        public string Teléfono { get; set; }
        public string Tutor_correo { get; set; }
        public string Tutor_telefono { get; set; }
    }
}
