//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNLCI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medico
    {
        public string Matricula { get; set; }
        public string Médico_Cv_Filiación { get; set; }
        public string Médico_Institución_Médica { get; set; }
        public string Médico_No_U_de_Salud { get; set; }
        public string Médico_Unidad_de_Salud { get; set; }
    }
}
