//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNLCI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pase_de_salida
    {
        public int No__pase { get; set; }
        public string Matricula { get; set; }
        public string Nombre { get; set; }
        public string Primer_apellido { get; set; }
        public string Segundo_apellido { get; set; }
        public string Plan_de_Estudios { get; set; }
        public string Grupo_Referente { get; set; }
        public string Motivo { get; set; }
        public string Autoriza { get; set; }
        public string Parentezco { get; set; }
        public string Medio_de_Autorizacion { get; set; }
        public byte[] Comprobante { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public int Valor { get; set; }
        public Nullable<bool> Activo { get; set; }
        public string Observaciones { get; set; }
        public string ElaboradoPor { get; set; }
    }
}
